project:
  type: website
  output-dir: docs 

website:
  title: "Mapping FBI Crime Data Reporting Across the U.S."
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-SU25/final-project-anorman111
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true


execute:
  freeze: auto
